### ISSUE TITLE
It isn' t working now

### ISSUE THREAD

**Issue by insproad** [santaimpersonator/Spotify-Album-Cover-Display#1]
I use two years ago but now after I upload the code. Http server started, nothing came to serial port. Can you check the code please?

**Comment by santaimpersonator** [comment]
I may need to archive this repo... this also stopped working for me a while ago. When I was digging into the issue, I believe the problem was with the API access from Spotify.

Unfortunately, as this was just a hobby project... this isn't a huge priority for me to fix
